version: '2'
 
services:
 
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./mysql/dbd.sql:/docker-entrypoint-initdb.d/backup.sql  
      
  wordpress:
    depends_on:
      - "mysql"
    image: wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: db
    volumes:
      - ./astanil:/var/www/html
