version: '2'
 
services:
  wordpress:
    image: wordpress
    ports: 
      - "8000:80"
    environment:
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: db
    volumes:
      - ./astanil:/var/www/html
 
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
    volumes:
      - ./astanil.com.sql.gzip:/docker-entrypoint-initdb.d/backup.sql.gzip
  
